name = "aula-maker-qr"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "aula_maker_db"
database_id = "e5222d61-dfcf-4313-9b16-9d31462293e4" # ID de la base de datos D1 proporcionado por el usuario
